stages:
  - build

api_build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $VERSION
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event") || $CI_MERGE_REQUEST_IID
      changes:
        - apps/api/**/*
  script:
    - echo "The job's stage is '$CI_PIPELINE_SOURCE == "merge_request_event"'"
    - echo "Print this $CI_MERGE_REQUEST_IID"
    - echo $CI_PIPELINE_SOURCE == "merge_request_event"
    - echo $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_MERGE_REQUEST_IID
