name: Api build

on:
  push:
    branches-ignore: ["*-develop", "[0-9]?[0-9].[0-9]?[0-9]"]
    tags-ignore: ['**']
    paths: [".github/workflows/action-api-build.yml", "apps/api/**", "libs/core/**"]

jobs:
  api_build:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker
        run: echo "Print THIS IS PRINT FROM API BUILD"
